--- orig/Qais-Trading-Academy-main/lib/assets.js	2026-07-03 12:00:11.000000000 +0000
+++ project/Qais-Trading-Academy-main/lib/assets.js	2026-07-03 18:58:37.980640414 +0000
@@ -5,40 +5,40 @@
 
 export const ASSETS = [
   { group: "المعادن", items: [
-    { v:"XAUUSD", label:"(ذهب) XAUUSD", yahoo:"GC=F" },
-    { v:"XAGUSD", label:"(فضة) XAGUSD", yahoo:"SI=F" },
-    { v:"XPTUSD", label:"(بلاتين) XPTUSD", yahoo:"PL=F" },
-    { v:"XPDUSD", label:"(بلاديوم) XPDUSD", yahoo:"PA=F" },
-    { v:"COPPER", label:"(نحاس) Copper", yahoo:"HG=F" },
+    { v:"XAUUSD", label:"(ذهب) XAUUSD", yahoo:"GC=F", mult:100  },
+    { v:"XAGUSD", label:"(فضة) XAGUSD", yahoo:"SI=F", mult:5000  },
+    { v:"XPTUSD", label:"(بلاتين) XPTUSD", yahoo:"PL=F", mult:100  },
+    { v:"XPDUSD", label:"(بلاديوم) XPDUSD", yahoo:"PA=F", mult:100  },
+    { v:"COPPER", label:"(نحاس) Copper", yahoo:"HG=F", mult:1  },
   ]},
   { group: "فوركس", items: [
-    { v:"EURUSD", label:"EUR/USD", yahoo:"EURUSD=X" },
-    { v:"GBPUSD", label:"GBP/USD", yahoo:"GBPUSD=X" },
-    { v:"USDJPY", label:"USD/JPY", yahoo:"USDJPY=X" },
-    { v:"USDCHF", label:"USD/CHF", yahoo:"USDCHF=X" },
-    { v:"AUDUSD", label:"AUD/USD", yahoo:"AUDUSD=X" },
-    { v:"USDCAD", label:"USD/CAD", yahoo:"USDCAD=X" },
-    { v:"NZDUSD", label:"NZD/USD", yahoo:"NZDUSD=X" },
-    { v:"EURJPY", label:"EUR/JPY", yahoo:"EURJPY=X" },
-    { v:"GBPJPY", label:"GBP/JPY", yahoo:"GBPJPY=X" },
-    { v:"EURGBP", label:"EUR/GBP", yahoo:"EURGBP=X" },
+    { v:"EURUSD", label:"EUR/USD", yahoo:"EURUSD=X", mult:100000  },
+    { v:"GBPUSD", label:"GBP/USD", yahoo:"GBPUSD=X", mult:100000  },
+    { v:"USDJPY", label:"USD/JPY", yahoo:"USDJPY=X", mult:1000  },
+    { v:"USDCHF", label:"USD/CHF", yahoo:"USDCHF=X", mult:100000  },
+    { v:"AUDUSD", label:"AUD/USD", yahoo:"AUDUSD=X", mult:100000  },
+    { v:"USDCAD", label:"USD/CAD", yahoo:"USDCAD=X", mult:100000  },
+    { v:"NZDUSD", label:"NZD/USD", yahoo:"NZDUSD=X", mult:100000  },
+    { v:"EURJPY", label:"EUR/JPY", yahoo:"EURJPY=X", mult:1000  },
+    { v:"GBPJPY", label:"GBP/JPY", yahoo:"GBPJPY=X", mult:1000  },
+    { v:"EURGBP", label:"EUR/GBP", yahoo:"EURGBP=X", mult:100000  },
   ]},
   { group: "كريبتو", items: [
-    { v:"BTCUSD", label:"Bitcoin (BTC/USD)", yahoo:"BTC-USD" },
-    { v:"ETHUSD", label:"Ethereum (ETH/USD)", yahoo:"ETH-USD" },
-    { v:"SOLUSD", label:"Solana (SOL/USD)", yahoo:"SOL-USD" },
-    { v:"XRPUSD", label:"Ripple (XRP/USD)", yahoo:"XRP-USD" },
-    { v:"BNBUSD", label:"BNB/USD", yahoo:"BNB-USD" },
-    { v:"DOGEUSD", label:"Dogecoin (DOGE/USD)", yahoo:"DOGE-USD" },
+    { v:"BTCUSD", label:"Bitcoin (BTC/USD)", yahoo:"BTC-USD", mult:1  },
+    { v:"ETHUSD", label:"Ethereum (ETH/USD)", yahoo:"ETH-USD", mult:1  },
+    { v:"SOLUSD", label:"Solana (SOL/USD)", yahoo:"SOL-USD", mult:1  },
+    { v:"XRPUSD", label:"Ripple (XRP/USD)", yahoo:"XRP-USD", mult:1  },
+    { v:"BNBUSD", label:"BNB/USD", yahoo:"BNB-USD", mult:1  },
+    { v:"DOGEUSD", label:"Dogecoin (DOGE/USD)", yahoo:"DOGE-USD", mult:1  },
   ]},
   { group: "مؤشرات وأسهم", items: [
-    { v:"US30", label:"US30 (داو جونز)", yahoo:"^DJI" },
-    { v:"NAS100", label:"NAS100 (ناسداك)", yahoo:"^NDX" },
-    { v:"SPX500", label:"SPX500 (S&P 500)", yahoo:"^GSPC" },
-    { v:"AAPL", label:"Apple (AAPL)", yahoo:"AAPL" },
-    { v:"TSLA", label:"Tesla (TSLA)", yahoo:"TSLA" },
-    { v:"MSFT", label:"Microsoft (MSFT)", yahoo:"MSFT" },
-    { v:"AMZN", label:"Amazon (AMZN)", yahoo:"AMZN" },
+    { v:"US30", label:"US30 (داو جونز)", yahoo:"^DJI", mult:1  },
+    { v:"NAS100", label:"NAS100 (ناسداك)", yahoo:"^NDX", mult:1  },
+    { v:"SPX500", label:"SPX500 (S&P 500)", yahoo:"^GSPC", mult:1  },
+    { v:"AAPL", label:"Apple (AAPL)", yahoo:"AAPL", mult:1  },
+    { v:"TSLA", label:"Tesla (TSLA)", yahoo:"TSLA", mult:1  },
+    { v:"MSFT", label:"Microsoft (MSFT)", yahoo:"MSFT", mult:1  },
+    { v:"AMZN", label:"Amazon (AMZN)", yahoo:"AMZN", mult:1  },
   ]},
 ];
 
